config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  # modules
  resources :course_modules, only: %i[index show]

  # modules
  resources :lessons, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course_module.rb
class CourseModule < ApplicationRecord
  has_many :lessons
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :tasks
  has_many :resources
  belongs_to :course_module
end

app/models/resource.rb
class Resource < ApplicationRecord
  belongs_to :lesson
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :lesson
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/course_modules_controller.rb
class CourseModulesController < ApplicationController
  before_action :set_course_module, only: %i[show]

  def index
    @course_modules = CourseModule.all
  end

  def show; end

  private

  def set_course_module
    @course_module = CourseModule.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  layout "application"

  def index
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[show]
  before_action :set_navigation, only: %i[show]

  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def set_navigation
    @previous_lesson = @lesson.course_module.lessons.where("id < ?", @lesson.id).last
    @next_lesson = @lesson.course_module.lessons.where("id > ?", @lesson.id).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/course_modules/index.html.erb
<div class="container mt-3">
  <div class="row row-cols-1 row-cols-md-3 g-4 pb-3">
    <% @course_modules.each do |course_module| %>
      <div class="col d-flex">
        <div class="card h-100 text-bg-light">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title text-dark"><%= course_module.name %></h5>
            <p class="card-text text-dark"><%= truncate(course_module.description, length: 100) %></p>
            <a href="<%= course_module_path(course_module) %>" class="btn btn-dark mt-auto">Поехали!</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/course_modules/show.html.erb
<!-- app/views/course_modules/show.html.erb -->
<div class="container mt-4">
  <h2 class="mb-3 text-center" style="color: black;"><%= @course_module.name %></h2>
  <ul class="list-unstyled">
    <% @course_module.lessons.each do |lesson| %>
      <li class="mb-2">
        <a href="<%= lesson_path(lesson) %>" class="text-decoration-none" style="color: black;">
          <div class="p-2 border border-dark rounded" style="background-color: white;">
            <h5 class="mb-1"><%= lesson.name %></h5>
            <p class="mb-0 text-muted" style="font-size: 0.9em;"><%= lesson.content %></p>
          </div>
        </a>
      </li>
    <% end %>
  </ul>
</div>

app/views/home/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-lg-12">
      <div class="content shadow-sm p-5 mb-5 bg-white rounded">
        <h1 class="text-center mb-4">Добро пожаловать</h1>
        <p class="lead">Мы рады приветствовать тебя на странице нашего курса по копирайтингу, который обещает быть не просто обучением, но настоящим погружением в мир текстов и маркетинга.</p>
        
        <!-- Course Outline -->
        <h2 class="mt-5">Профессия копирайтер за месяц с нуля</h2>
        <!-- Week 1 -->
        <h3>Неделя 1: Основы копирайтинга и понимание аудитории (10 часов)</h3>
        <ul>
          <li>Введение в копирайтинг: определение и цели.</li>
          <li>Разбор типов копирайтинга: SEO, SMM, контент-маркетинг.</li>
          <li>Методы сегментации аудитории и создание портретов.</li>
          <li>Маркетинговые исследования: инструменты для анализа рынка.</li>
        </ul>
        
        <!-- Week 2 -->
        <h3>Неделя 2: Навыки написания и SEO-оптимизация (10 часов)</h3>
        <ul>
          <li>Креативное письмо: заголовки, вводные абзацы, призывы к действию.</li>
          <li>Основы SEO и создание SEO-дружественного контента.</li>
          <li>Структурирование контента: статьи, посты, реклама.</li>
        </ul>
        
        <!-- Week 3 -->
        <h3>Неделя 3: Платформы публикации и аналитика (10 часов)</h3>
        <ul>
          <li>Работа с CMS: WordPress, Medium.</li>
          <li>Контент-маркетинг: стратегии распространения.</li>
          <li>Аналитика контента: Google Analytics.</li>
        </ul>
        
        <!-- Week 4 -->
        <h3>Неделя 4: Брендинг и личный бренд (10 часов)</h3>
        <ul>
          <li>Стратегия брендинга: влияние бренда на контент.</li>
          <li>Разработка личного бренда копирайтера.</li>
          <li>Подготовка портфолио для будущих работодателей.</li>
        </ul>
        
        <!-- Career Development -->
        <h3>Пути развития и прохождение собеседований</h3>
        <ul>
          <li>Составление резюме и сопроводительных писем.</li>
          <li>Тренировка навыков прохождения собеседований.</li>
          <li>Поиск работы: LinkedIn, Upwork, нетворкинг.</li>
        </ul>
        
        <p class="mt-4">По завершении курса ты станешь настоящим мастером слова, способным создавать контент, который не только привлекает внимание, но и действует на аудиторию, превращая читателей в клиентов. Твое понимание SEO и аналитики позволит тебе создавать материалы, высоко оцениваемые поисковыми системами. А твое портфолио и уверенность в собеседованиях откроют перед тобой двери в мир профессионального копирайтинга.</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CopywriterLearningApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <%= link_to "Курс копирайтера", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Модули", course_modules_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Main Content -->
    <div class="container mt-4 flex-shrink-0">
      <%= yield %>
    </div>

    <!-- Footer -->
    <footer class="mt-auto py-3 text-center text-lg-start bg-dark text-muted">
      <div class="text-center p-4 text-light" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2024 CopywriterLearningApp. All rights reserved.
      </div>
    </footer>
  </body>
</html>

app/views/lessons/_navigation.html.erb
<div class="d-flex justify-content-between my-4">
  <div>
    <% if previous_lesson %>
      <%= link_to 'Предыдущий урок', lesson_path(previous_lesson), class: "btn btn-outline-secondary" %>
    <% end %>
  </div>
  <div>
    <% if next_lesson %>
      <%= link_to 'Следующий урок', lesson_path(next_lesson), class: "btn btn-outline-secondary" %>
    <% end %>
  </div>
</div>

app/views/lessons/show.html.erb
<div class="container mt-4">
  <div class="mb-3">
    <small class="text-muted">Модуль: <%= @lesson.course_module.name %></small>
    <h3 class="mb-2 text-dark"><%= @lesson.name %></h3>
    <p class="text-dark"><%= @lesson.content %></p>
  </div>

  <h4 class="mt-4 mb-2 text-dark">Материалы</h3>
  <%= render partial: "resources/resource", collection: @lesson.resources, as: :resource %>

  <h4 class="mt-4 mb-2 text-dark">Задания</h3>
  <%= render partial: "tasks/task", collection: @lesson.tasks, as: :task %>
</div>

<%= render partial: "lessons/navigation", locals: { previous_lesson: @previous_lesson, next_lesson: @next_lesson } %>

app/views/resources/_resource.html.erb
<div class="p-2 border border-dark rounded mt-2" style="background-color: white;">
  <h5 class="mb-1 text-dark"><%= resource.name %></h5>
  <% if resource.content.present? %>
    <p class="text-dark"><%= resource.content %></p>
  <% end %>
  <% if resource.url.present? %>
    <%= link_to "Перейти", resource.url, class: "text-dark" %>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<div class="p-2 border border-dark rounded mt-2" style="background-color: white;">
  <h5 class="text-dark"><%= task.description %></h5>
  <p class="text-muted"><%= task.example %></p>
</div>